import org.apache.hadoop.fs.shell.PathExceptions.PathIOException;
public class FunctionUse10555 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
pathioexception.getPath();
}
}